server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:h2:./jupiter
    username: sample
    password: sample
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create